apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':stockflow-core')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Batch
    implementation 'org.springframework.boot:spring-boot-starter-batch'

    // JPA + PostgreSQL (TimescaleDB)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
}
